# Generated by Django 3.2.9 on 2021-11-16 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('body', models.TextField(blank=True, verbose_name='Содержимое')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='фото')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='TopMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(max_length=125, verbose_name='пункт меню')),
                ('choes', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.page', verbose_name='Верхнее меню')),
            ],
            options={
                'verbose_name': 'Верхнее меню',
                'verbose_name_plural': 'Верхнее меню',
            },
        ),
    ]
